### ISSUE TITLE
second get fails

### ISSUE THREAD

**Issue by sniperlucian** [dfederschmidt/airsensor-py#4]
dont know if this still active,

but calling 

`airsensor.get_voc()`

leads to timeout and error (first call is just fine, and c version also works correctly):

```
Traceback (most recent call last):
  File "airsens.py", line 28, in <module>
    voc = airsensor.get_voc()
  File "/home/lucian/miniconda3/lib/python3.8/site-packages/airsensor/core.py", line 23, in get_voc
    n = self.dev.write(0x02, cmd, timeout=10000)
  File "/home/lucian/miniconda3/lib/python3.8/site-packages/usb/core.py", line 989, in write
    return fn(
  File "/home/lucian/miniconda3/lib/python3.8/site-packages/usb/backend/libusb1.py", line 855, in intr_write
    return self.__write(self.lib.libusb_interrupt_transfer,
  File "/home/lucian/miniconda3/lib/python3.8/site-packages/usb/backend/libusb1.py", line 938, in __write
    _check(retval)
  File "/home/lucian/miniconda3/lib/python3.8/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out
```

**Comment by dfederschmidt** [comment]
Hi, thanks for reporting this issue. Unfortunately, I lost the sensor I originally developed this package for (yeah, bad on my part). Happy to add a fix here if we find one.
